<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reviews Export</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }

        h1 {
            font-size: 20px;
            margin-bottom: 5px;
        }

        .meta {
            margin-bottom: 15px;
            font-size: 11px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }

        th, td {
            border: 1px solid #999;
            padding: 6px 8px;
            vertical-align: top;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-align: left;
        }

        .text-center {
            text-align: center;
        }

        .small {
            font-size: 10px;
        }

        .break-word {
            word-wrap: break-word;
            word-break: break-word;
        }
    </style>
</head>
<body>
    <h1>Reviews Export</h1>

    <div class="meta">
        <div>Generated by: {{ $exportedBy->name ?? $exportedBy->email ?? 'Unknown User' }}</div>
        <div>Generated at: {{ $generatedAt }}</div>
        <div>Total reviews: {{ $reviews->count() }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th>Review ID</th>
                <th>User</th>
                <th>Movie</th>
                <th class="text-center">Rating</th>
                <th>Review</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
        @forelse ($reviews as $index => $review)
            @php
                $movieLabel = $movieDetails[$review->id_movie] ?? $review->id_movie;
            @endphp
            <tr>
                <td class="text-center small">{{ $index + 1 }}</td>
                <td class="small">{{ $review->id_review ?? $review->id ?? '' }}</td>
                <td class="small">
                    @if($review->user)
                        {{ $review->user->name ?? $review->user->email ?? $review->id_user }}
                    @else
                        {{ $review->id_user }}
                    @endif
                </td>
                <td class="small">{{ $movieLabel }}</td>
                <td class="text-center small">{{ $review->rating }}</td>
                <td class="small break-word">
                    {{ $review->review }}
                </td>
                <td class="small">{{ $review->created_at }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="7" class="text-center small">No reviews found for the selected filters.</td>
            </tr>
        @endforelse
        </tbody>
    </table>
</body>
</html>
